/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class morphr_MorphR */

#ifndef _Included_morphr_MorphR
#define _Included_morphr_MorphR
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     morphr_MorphR
 * Method:    initiateCubist
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_morphr_MorphR_initiateCubist
  (JNIEnv *, jobject, jstring);

/*
 * Class:     morphr_MorphR
 * Method:    getPrediction
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_morphr_MorphR_getPrediction
  (JNIEnv *, jobject, jstring);

/*
 * Class:     morphr_MorphR
 * Method:    getPredictionAndError
 * Signature: (Ljava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_morphr_MorphR_getPredictionAndError
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
